// Рисунки игр TimeBox — пиксель-арт. Каждый рисунок — 15×15 клеток, вокруг программа сама добавляет
// контур в одну клетку (итого 17×17), поэтому у всего набора одинаковый тёмный контур. В игре рисунок
// занимает 34×34: по 2 пикселя на клетку — как смайлик размером 34px, и все рамки столкновений прежние.
// Имя рисунка — по-русски, его пишет ученик: drawPic("ракета", x, y). Чистый модуль: без DOM.

/** Цвета клеток. `k` — чернила: ими же рисуется контур. */
export const PALETTE: Record<string, string> = {
  k: '#1b1424',
  w: '#fff4e6',
  r: '#e8423f',
  R: '#a3263a',
  o: '#f78b2b',
  O: '#c4561b',
  y: '#ffd23f',
  Y: '#d9961e',
  l: '#9be05a',
  g: '#34a853',
  G: '#1f6e3c',
  s: '#5ccdf2',
  b: '#3a63d9',
  B: '#24307a',
  p: '#9b5de5',
  P: '#5c3591',
  m: '#ff86b8',
  M: '#d9487f',
  n: '#a0602f',
  N: '#5e3720',
  e: '#f1c48c',
  a: '#c3c8d9',
  A: '#6b7290',
}

/** Группы в окне выбора — в таком порядке. */
export const PICTURE_GROUPS: { title: string; names: string[] }[] = [
  { title: 'Герои', names: ['колобок', 'кот', 'лиса', 'лягушка', 'робот', 'пингвин', 'корзинка'] },
  { title: 'Еда', names: ['яблоко', 'груша', 'вишня', 'клубника', 'пончик', 'рыба'] },
  { title: 'Вещи', names: ['бомба', 'звезда', 'монетка', 'сердце', 'молния'] },
  { title: 'Летают', names: ['цыплёнок', 'птичка', 'сова', 'пчела', 'мышь', 'дракон'] },
  { title: 'Космос', names: ['ракета', 'тарелка', 'пришелец', 'осьминог', 'астероид', 'взрыв', 'луна'] },
]

/** Все имена рисунков, которые можно выбрать. */
export const PICTURE_NAMES = PICTURE_GROUPS.flatMap((g) => g.names)

/** Его игра рисует вместо картинки с неизвестным именем — например, с опечаткой. */
export const UNKNOWN_PICTURE = '?'

// '.' — пусто, буква — цвет из PALETTE
const ART: Record<string, string> = {
  колобок: `
.....yyyyy.....
...yyyyyyyyy...
..ywwyyyyyyyy..
.ywwyyyyyyyyyy.
.yyyyyyyyyyyyy.
yyyykkyyykkyyyy
yyyywkyyywkyyyy
yyyyyyyyyyyyyyy
ymmyyyyyyyyymmy
yyykyyyyyyykyyy
.yyykkkkkkkyyy.
.yyyyyyyyyyyyy.
..YyyyyyyyyyY..
...YYYyyyYYY...
.....YYYYY.....
`,
  кот: `
...............
.O...........O.
.oO.........Oo.
.omo.......omo.
.ooooooooooooo.
ooooooooooooooo
oookkoooookkooo
ooowkooooowkooo
ooooooooooooooo
eeoooooMoooooee
oooooookooooooo
.oooookokooooo.
.ooooooooooooo.
..OOoooooooOO..
....OOOOOOO....
`,
  лиса: `
...............
.N...........N.
.oO.........Oo.
.ooo.......ooo.
.ooooooooooooo.
ooooooooooooooo
ooookkoookkoooo
oooowkooowkoooo
wooooooooooooow
wwoooooooooooww
wwwwooooooowwww
.wwwwwokowwwww.
..wwwwwkwwwww..
....wwwwwww....
......www......
`,
  лягушка: `
...............
..ggg.....ggg..
.gwwwg...gwwwg.
.gwkkgggggwkkg.
.ggggggggggggg.
ggggggggggggggg
gglggggggggglgg
ggggggggggggggg
gkgggggggggggkg
ggkkkkkkkkkkkgg
.gglllllllllgg.
.gglllllllllgg.
GGgglllllllggGG
GGG.ggggggg.GGG
...............
`,
  робот: `
.......r.......
.......A.......
..aaaaaaaaaaa..
.awaaaaaaaaaaa.
.aaaaaaaaaaaaa.
.aasssaaasssaa.
.aaswsaaaswsaa.
.aasssaaasssaa.
.aaaaaaaaaaaaa.
.aaAAAAAAAAAaa.
.aaAkAkAkAkAaa.
.aaaaaaaaaaaaa.
..AAAAAAAAAAA..
...A.......A...
..AAA.....AAA..
`,
  пингвин: `
.....BBBBB.....
...BBBBBBBBB...
..BBBBBBBBBBB..
..BBwwBBBwwBB..
..BBwkBBBwkBB..
..BBBBoooBBBB..
.BBBwwwOwwwBBB.
.BBwwwwwwwwwBB.
BBBwwwwwwwwwBBB
BBwwwwwwwwwwwBB
BBwwwwwwwwwwwBB
.BwwwwwwwwwwwB.
..BwwwwwwwwwB..
...BBBBBBBBB...
...ooo...ooo...
`,
  корзинка: `
....nnnnnnn....
...n.......n...
..n.........n..
..n.........n..
..n.........n..
NNNNNNNNNNNNNNN
nenenenenenenen
.enenenenenene.
.nenenenenenen.
.enenenenenene.
..nenenenenen..
..enenenenene..
..nenenenenen..
...NNNNNNNNN...
...............
`,
  яблоко: `
.......n.......
.......nggg....
......nGgg.....
...rrrrnrrrr...
..rrrrrrrrrrr..
.rwwrrrrrrrrrr.
.rwrrrrrrrrrrr.
rrrrrrrrrrrrrrr
rrrrrrrrrrrrrrr
rrrrrrrrrrrrrrr
.rrrrrrrrrrrrR.
.rrrrrrrrrrrRR.
..rrrrrrrrrRR..
...RRrrrrrRR...
.....RR.RR.....
`,
  груша: `
........n......
.......n.......
......lll......
.....lllll.....
.....lwlll.....
.....lwlll.....
....lllllll....
...lllllllll...
..lllllllllll..
..lllllllllll..
.lllllllllllll.
.llllllllllllg.
.lllllllllllgg.
..lllllllllgg..
....ggggggg....
`,
  вишня: `
...............
...............
..........gg...
.........Gg....
........G.G....
.......G..G....
......G...G....
.....G....G....
..rrrr...rrrr..
.rwrrrr.rwrrrr.
.rwrrrr.rwrrrr.
.rrrrrr.rrrrrr.
.rrrrRr.rrrrRr.
..RRRR...RRRR..
...............
`,
  клубника: `
....gg.g.gg....
...ggggggggg...
..rrGgggggGrr..
.rrrrrrrrrrrrr.
.rwrryrrryrrrr.
.rwrrrrrrrrrrr.
.rrryrrryrrryr.
..rrrrrrrrrrr..
..ryrrryrrryr..
...rrrrrrrrr...
...rrryrrrrr...
....rrrrrrR....
.....rrrrR.....
......RRR......
...............
`,
  пончик: `
...............
....eeeeeee....
..emmmmmmmmme..
.emmwmmmymmmme.
.emwmmmmmsmmme.
emmmym...mmlmme
emmsm.....mmmme
eemmm.....mmmee
eeeee.....eeeee
eeeeee...eeeeee
neeeeeeeeeeeeen
.neeeeeeeeeeen.
..nneeeeeeenn..
....nnnnnnn....
...............
`,
  рыба: `
...............
...............
...............
...............
....ssssss.....
..ssssssssss..b
.sswksssssssbbb
ssskksssssssbb.
sssssssssssbbb.
.sssbsbsbsssbbb
..ssssssssss..b
....ssssss.....
...............
...............
...............
`,
  бомба: `
...........y...
..........yoy..
...........n...
..........n....
......AAAA.....
....AAAAAAAA...
...AawAAAAAAAAA
..AAwAAAAAAAAA.
.AAAAAAAAAAAAA.
.AAAAAAAAAAAAA.
.AAAAAAAAAAAAA.
.AAAAAAAAAAAAA.
..AAAAAAAAAAA..
...AAAAAAAAA...
.....AAAAA.....
`,
  звезда: `
.......y.......
......yyy......
......yyy......
.....yyyyy.....
yyyyyyyyyyyyyyy
.yyyywyyyyyyyy.
..yyywyyyyyyy..
...yyyyyyyyy...
....yyyyyyy....
....yyyyyyy....
...yyyyyyyyy...
...yyyY.Yyyy...
..yyyY...Yyyy..
..yyY.....Yyy..
.yY.........Yy.
`,
  монетка: `
...............
.....yyyyy.....
...yyyyyyyyy...
..ywwyyyyyyyY..
.ywyyyyYyyyyyY.
.yyyyyYYYyyyyY.
yyyyyyyYyyyyyYY
yyyyyyyYyyyyyYY
yyyyyyyYyyyyyYY
.yyyyyyYyyyyyY.
.yyyyyYYYyyyyY.
..yyyyyyyyyYY..
...YyyyyyyyY...
.....YYYYY.....
...............
`,
  сердце: `
...............
...............
..rrrr...rrrr..
.rwwrrr.rrrrrr.
rwwrrrrrrrrrrrr
rwrrrrrrrrrrrrr
rrrrrrrrrrrrrrR
.rrrrrrrrrrrrR.
..rrrrrrrrrrR..
...rrrrrrrrR...
....rrrrrrR....
.....rrrrR.....
......rrR......
.......R.......
...............
`,
  цыплёнок: `
...............
.....yyyy......
....yyyyyy.....
...yyyyykyy....
...ywyyyyyyoo..
...yyyyyyyyyo..
..yyyyyyyyyy...
.yyyyyyyyyyyy..
yyyYYYyyyyyyyy.
yyyyYYYyyyyyyy.
yyyyyyyyyyyyyy.
.yyyyyyyyyyyyy.
..YyyyyyyyyyY..
....YYYYYYY....
.....o...o.....
`,
  птичка: `
...............
...............
.......bbbb....
......bbbbbb...
.....bbbbwkbb..
.....bbbbkkbbyy
....bbbbbbbbby.
..sbbbbbbbbbb..
.ssbbwwwwbbbb..
sssbwwwwwwbbb..
ssbbwwwwwwbbb..
.bbbbwwwwbbb...
...bbbbbbbb....
.....yy..yy....
...............
`,
  сова: `
.n...........n.
.nn.........nn.
.nnnnnnnnnnnnn.
.nwwwnnnnnwwwn.
nwwkwwnnnwwkwwn
nwwkkwnonwkkwwn
nwwwwwnonwwwwwn
.nwwwnnnnnwwwn.
nnnnnneeennnnnn
nNnnneeeeennnNn
nNnneeNeNeennNn
nNnneeeeeeennNn
.nnnneeeeennnn.
..nnnnnnnnnnn..
....oo...oo....
`,
  пчела: `
...............
...............
...sss...sss...
..swwws.swwws..
...swwwswwws...
....sssssss....
...............
...yyyyyyyyy...
..yyykyykyyyy..
.yyyykyykyywky.
kyyyykyykyykky.
.yyyykyykyyyyy.
..yyykyykyyyy..
...yyyyyyyyy...
...............
`,
  мышь: `
...............
...............
...............
...............
P.....p.p.....P
PP...ppppp...PP
PPP.pypppyp.PPP
PPPPpppppppPPPP
PPPPPpwpwpPPPPP
PPPPPPpppPPPPPP
PP.PP.ppp.PP.PP
P...P..p..P...P
...............
...............
...............
`,
  дракон: `
...............
....w..........
....ww.G.......
...gggggg......
..gggggwkg.....
.ggggggkkgggg..
.gggggggggggggg
gglggggggggggkg
glllgggggggggg.
glllllgggggggg.
.gllllgwgwgwg..
..glllgggggg...
...gGgGgG......
...GGGGGG......
...............
`,
  ракета: `
.......r.......
......rrr......
.....rrrrr.....
.....wwwww.....
.....wsbbw.....
.....wbbbw.....
.....wwwww.....
.....wwwww.....
....rwwwwwr....
...rrwwwwwrr...
..rrrwwawwrrr..
..rr.aaaaa.rr..
......oyo......
......yoy......
.......o.......
`,
  тарелка: `
...............
...............
...............
...............
...............
.....sssss.....
....swwssss....
....sssssss....
..aaaaaaaaaaa..
.aaaaaaaaaaaaa.
aaayaaayaaayaaa
.AAAAAAAAAAAAA.
..AAAAAAAAAAA..
...............
...............
`,
  пришелец: `
...............
...............
...............
...............
...p.......p...
....p.....p....
...ppppppppp...
..pppwpppwppp..
.ppppppppppppp.
.p.ppppppppp.p.
.p.p.......p.p.
....pp...pp....
...............
...............
...............
`,
  осьминог: `
...............
.....mmmmm.....
...mmmmmmmmm...
..mwwmmmmmmmm..
..mwmmmmmmmmm..
.mmmwkmmmwkmmm.
.mmmkkmmmkkmmm.
.mmmmmmmmmmmmm.
..mmmmMMMmmmm..
..mmmmmmmmmmm..
.mm.mm.m.mm.mm.
.m..m..m..m..m.
mm..mm.m.mm..mm
...............
...............
`,
  астероид: `
...............
...............
.....AAAA......
...AAaaaaAA....
..AaaaaaaaaaA..
.AaaAAaaaaaaaA.
.AaaAAaaaaAaaA.
AaaaaaaaaAAaaaA
AaawaaaaaAAaaaA
AaaaaaAaaaaaaA.
.AaaaAAAaaaaaA.
.AAaaaAaaaaaAA.
..AAaaaaaaAA...
....AAAAAAA....
...............
`,
  взрыв: `
......y........
..y...yy...y...
...yy.yoy.yy...
...yoyooooyy...
y..yoorrroyo..y
.yyoorrwrrooyy.
..yorrwwwrroy..
yyoorwwwwwrooyy
..yorrwwwrroy..
.yyoorrwrrooyy.
y..yoorrrooy..y
...yyooooyy....
...yy.yoy.yy...
..y...yy...y...
......y........
`,
  луна: `
......yyyy.....
....yyyyY......
...yyyyY.......
..ywyyY........
.ywyyY.........
.yyyY..........
yyyyY..........
yyyyY..........
yyyyY..........
.yyyyY.........
.yyyyyY......y.
..yyyyyYY..yy..
...yyyyyyyyyy..
....yyyyyyyy...
......yyyy.....
`,
  молния: `
.........yyyy..
........yyyy...
.......yyyy....
......yyyy.....
.....ywyy......
....yyyy.......
...yyyyyyyyy...
..yyyyyyyyy....
.......yyy.....
......yyy......
.....yyY.......
....yyY........
...yyY.........
..yY...........
..Y............
`,
  '?': `
...............
..aaaaaaaaaaa..
.aaaaaaaaaaaaa.
.aaaaAAAAAaaaa.
.aaaAAaaaAAaaa.
.aaaaaaaaAAaaa.
.aaaaaaaAAaaaa.
.aaaaaaAAaaaaa.
.aaaaaaAAaaaaa.
.aaaaaaaaaaaaa.
.aaaaaaAAaaaaa.
.aaaaaaAAaaaaa.
..aaaaaaaaaaa..
...............
...............
`,
}

export const isPicture = (name: string) => name !== UNKNOWN_PICTURE && Object.hasOwn(ART, name)

const grids = new Map<string, string[]>()

/** Рисунок 17×17 с контуром: строки, '.' — пусто. Неизвестное имя — рисунок «?». */
export function pictureGrid(name: string): string[] {
  const key = Object.hasOwn(ART, name) ? name : UNKNOWN_PICTURE
  const cached = grids.get(key)
  if (cached) return cached
  const art = ART[key].trim().split('\n')
  const at = (x: number, y: number) => (y >= 1 && y <= 15 && x >= 1 && x <= 15 ? art[y - 1][x - 1] : '.')
  const grid: string[] = []
  for (let y = 0; y < 17; y++) {
    let row = ''
    for (let x = 0; x < 17; x++) {
      const c = at(x, y)
      // пустая клетка рядом (по стороне) с закрашенной — контур
      const edge = c === '.' && [at(x + 1, y), at(x - 1, y), at(x, y + 1), at(x, y - 1)].some((n) => n !== '.')
      row += edge ? 'k' : c
    }
    grid.push(row)
  }
  grids.set(key, grid)
  return grid
}
